### ISSUE TITLE
Can't import because of GLIBC requirements

### ISSUE THREAD

**Issue by hypercompetent** [biovault/nptsne#1]
Hi nptsne team,

I'm having some trouble getting nptsne to import (see below for error).

This seems to be due to a requirement for a high version of GLIBC (2.29), which isn't directly available through apt-get for my system (the max version available currently is 2.24).

If there's any way I might be able to work around this, that would be great, as manually updating GLIBC is difficult in my computing environment.

Thanks!
-Lucas

```
lucasg@graybuck-ide:/home/lucas.graybuck/nptsne_leiden_testing$ miniconda/envs/r-reticulate-9530452876/bin/python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import nptsne
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lucas.graybuck/nptsne_leiden_testing/miniconda/envs/r-reticulate-9530452876/lib/python3.7/site-packages/nptsne/__init__.py", line 1, in <module>
    from .nptsne import *
ImportError: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /home/lucas.graybuck/nptsne_leiden_testing/miniconda/envs/r-reticulate-9530452876/lib/python3.7/site-packages/nptsne/./libpng16.so.16)
>>> quit()
lucasg@graybuck-ide:/home/lucas.graybuck/nptsne_leiden_testing$ sudo apt-cache policy libc6
libc6:
  Installed: 2.24-11+deb9u4
  Candidate: 2.24-11+deb9u4
  Version table:
 *** 2.24-11+deb9u4 500
        500 http://deb.debian.org/debian stretch/main amd64 Packages
        100 /var/lib/dpkg/status
     2.24-11+deb9u1 500
        500 http://security.debian.org stretch/updates/main amd64 Packages
```

**Comment by bldrvnlw** [comment]
Sorry for the delay. There's a new version of nptsne - 1.1.0 available on PyPI. It has been built as a manylinux wheel which should solve any lib problems. Let me know if the issue is still there. New documentation is at [Read the Docs](https://nptsne.readthedocs.io/en/release-1.1.0/index.html)

**Comment by hypercompetent** [comment]
Hi Baldur,

Thanks for this update - this does indeed solve this issue.

I'm really enjoying working with the new HSNE functions!

Cheers,
-Lucas
